//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMusicWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA
    {
        public int ID_BOLETA { get; set; }
        public int ID_FORMA { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_AVISO { get; set; }
        public byte[] FECHA_TRANS { get; set; }
        public string DETALLE { get; set; }
        public string DETALLES { get; set; }
    
        public virtual AVISO AVISO { get; set; }
        public virtual FORMA_PAGO FORMA_PAGO { get; set; }
    }
}
